language: node_js 
env:
    global:
        secure: "L9vqq1qTZwNZbV6fk4gwV5G9atm95MQxs4jkFpC5aADcliiJLKKbPW/hNLJijMmzQFdqEL8Zz7HFOtgyKWG7RFWOkmpA2xk1A72qfwmMwmVqMnpYhdjeW6GzqGj7Tufna1/48p/77UHq1yJK6RuxyEtB4SN8UdPbO8NnTPwA/mw="
cache: 
  - apt
  - npm
    
matrix:
  fast_finish: true
  
# whitelist
branches:
  only:
    - master
    
before_install:
  - echo before install
  #- export owner=brownman
  #- export repo=github_integrations
  - source config.cfg
  - chmod u+x *.sh . -R

  

  
install:
  - echo let us start

script:
  - bash -c ./travis.sh
  
after_success:
  -  bash -c ./BANK/travis_and_github/update-gh-pages.sh




