language: node_js 
env:
    global:
        secure: "L9vqq1qTZwNZbV6fk4gwV5G9atm95MQxs4jkFpC5aADcliiJLKKbPW/hNLJijMmzQFdqEL8Zz7HFOtgyKWG7RFWOkmpA2xk1A72qfwmMwmVqMnpYhdjeW6GzqGj7Tufna1/48p/77UHq1yJK6RuxyEtB4SN8UdPbO8NnTPwA/mw="

cache: 
  - apt
  - npm
  
env:
  global:
    secure: ""
    
before_install: 
  - chmod u+x *.sh . -R
  
script:
  - touch /tmp/1.txt
  
after_success:
  -  bash -c ./BANK/travis_and_github/github_private_key.sh
