language: node_js 
env:
    global:
        secure: "DwLnSLTJ82wdNEKSlOSP12bGIvj9Iw97FioZNy0vQMLYfHIQsxDkczYzjaPg1+rCp0NUOrZDUtmMvBU4KZtU+AqV3yLKlnd2lx7flWCFoQbjoSmQ9z5ii5Lk8KGgZ8L18FfIjqJpkH8Q5XBUUzbXcyRMdh1tBiqFoyvO9LRHHZE="
cache: 
  - apt
  - npm
    
matrix:
  fast_finish: true
  
# whitelist
branches:
  only:
    - master
    
before_install:
  - cat .git/config
 
install:
  - git branch -r
  
script:
  - export dir_product=/tmp/product
  - touch $dir_product/1.txt
  - chmod u+x ./travis.sh
  - bash -c ./travis.sh

#  
#after_success:
#  -  bash -e ./BANK/travis_and_github/update-gh-pages.sh




