language: node_js 
cache: 
  - apt
  - npm
  
env:
  global:
    secure: ""
    
before_install: 
  - chmod u+x *.sh . -R
  
script:
  - touch /tmp/1.txt
  
after_success:
  -  bash -c ./BANK/travis_and_github/github_private_key.sh
